# default props
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  datasource:
    url: jdbc:h2:file:/storage/events
    driverClassName: org.h2.Driver
    username: service_user
    password: some_complex_password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8083

---

spring:
  config:
    activate:
      on-profile: activemq
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

---

spring:
  config:
    activate:
      on-profile: kafka
  kafka:
    bootstrap-servers: 127.0.0.1:29092
    listener:
      type: batch

---
spring:
  config:
    activate:
      on-profile: rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

